[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "groq>=0.31.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "vk-api>=11.10.0",
]
